# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
