# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_registryitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(),
        ),
    ]
