# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_donation_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
