# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_registryitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.CharField(default='me@email.com', max_length=100),
            preserve_default=False,
        ),
    ]
