# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_donation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='address',
        ),
    ]
