# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_donation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(default='Example Addresss'),
            preserve_default=False,
        ),
    ]
