# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_donation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
