# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190205_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
