# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_donation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
